CREATE TABLE INVOICE_DETAIL (
    maHoaDon nvarchar(MAX) NOT NULL,
    maLichSuFile nvarchar(MAX) NOT NULL,
    tenHoaDon nvarchar(MAX) NOT NULL,
    kiHieuMauSoHoaDon decimal(18, 0) NOT NULL,
    kiHieuHoaDon nvarchar(MAX) NOT NULL,
    soHoaDon nvarchar(MAX) NOT NULL,
    ngayLap nvarchar(MAX) NOT NULL,
    ngayDuyet nvarchar(MAX) NULL,
    ngayNhan nvarchar(MAX) NOT NULL,
    ngayThanhToan nvarchar(MAX) NULL,
    ngayKy nvarchar(MAX) NULL,
    hoaDonDanhChoKhuPhiThueQuan nvarchar(50) NULL,
    donViTienTe nvarchar(MAX) NULL,
    tiGia decimal(18, 1) NULL,
    hinhThucThanhToan nvarchar(MAX) NULL,
    mstToChucGiaiPhap nvarchar(MAX) NULL,
    tenNguoiBan nvarchar(MAX) NOT NULL,
    mstNguoiBan nvarchar(MAX) NOT NULL,
    diaChiNguoiBan nvarchar(MAX) NOT NULL,
    tenNguoiMua nvarchar(MAX) NOT NULL,
    mstNguoiMua nvarchar(MAX) NOT NULL,
    diaChiNguoiMua nvarchar(MAX) NOT NULL,
    nhanHoaDon bit NULL,
    ghiChu nvarchar(MAX) NULL,
    tongTienChuaThue nvarchar(MAX) NOT NULL,
    tongTienThue nvarchar(MAX) NOT NULL,
    tongTienChietKhauThuongMai nvarchar(MAX) NULL,
    tongTienThanhToanBangSo nvarchar(MAX) NOT NULL,
    tongTienThanhToanBangChu nvarchar(MAX) NOT NULL,
    trangThaiHoaDon numeric(18, 0) NOT NULL,
    trangThaiPheDuyet numeric(18, 0) NOT NULL,
    loaiHoaDon numeric(18, 0) NOT NULL,
    lyDoKhongDuyet nvarchar(MAX) NULL,
    nguoiDuyet nvarchar(MAX) NULL,
    phuongThucNhap decimal(18, 0) NOT NULL,
    checkTrangThaiXuLy decimal(18, 0) NOT NULL,
    checkTrangThaiHoaDon decimal(18, 0) NOT NULL,
    checkMstNguoiMua decimal(18, 0) NULL,
    checkDiaChiNguoiMua decimal(18, 0) NULL,
    checkTenNguoiMua decimal(18, 0) NULL,
    checkHDonKyDienTu decimal(18, 0) NOT NULL,
    kiemTraChungThu decimal(18, 0) NOT NULL,
    kiemTraTenNban decimal(18, 0) NOT NULL,
    kiemTraMstNban decimal(18, 0) NOT NULL,
    kiemTraHoatDongNmua decimal(18, 0) NOT NULL,
    kiemTraHoatDongNban decimal(18, 0) NOT NULL,
    dsFileDinhKem nvarchar(MAX) NULL,
    fileExcel nvarchar(MAX) NULL
);
