CREATE TABLE INVOICE_DETAIL (
    maHoaDon nvarchar(MAX) NOT NULL,
    maLichSuFile nvarchar(MAX) NOT NULL,
    tenHoaDon nvarchar(MAX) NOT NULL,
    kiHieuMauSoHoaDon int NOT NULL,
    kiHieuHoaDon nvarchar(MAX) NOT NULL,
    soHoaDon nvarchar(MAX) NOT NULL,
    ngayLap nvarchar(MAX) NULL,
    ngayDuyet nvarchar(MAX) NULL,
    ngayNhan nvarchar(MAX) NULL,
    ngayThanhToan nvarchar(MAX) NULL,
    ngayKy nvarchar(MAX) NULL,
    hoaDonDanhChoKhuPhiThueQuan nvarchar(100) NULL,
    donViTienTe nvarchar(MAX) NULL,
    tiGia decimal(18, 1) NULL,
    hinhThucThanhToan nvarchar(MAX) NULL,
    mstToChucGiaiPhap nvarchar(MAX) NULL,
    tenNguoiBan nvarchar(MAX) NOT NULL,
    mstNguoiBan nvarchar(MAX) NOT NULL,
    diaChiNguoiBan nvarchar(MAX) NOT NULL,
    tenNguoiMua nvarchar(MAX) NOT NULL,
    mstNguoiMua nvarchar(MAX) NOT NULL,
    diaChiNguoiMua nvarchar(MAX) NOT NULL,
    nhanHoaDon nvarchar(MAX) NULL,
    ghiChu nvarchar(MAX) NULL,
    tongTienChuaThue nvarchar(MAX) NOT NULL,
    tongTienThue nvarchar(MAX) NOT NULL,
    tongTienChietKhauThuongMai nvarchar(MAX) NULL,
    tongTienThanhToanBangSo nvarchar(MAX) NOT NULL,
    tongTienThanhToanBangChu nvarchar(MAX) NOT NULL,
    trangThaiHoaDon int NOT NULL,
    trangThaiPheDuyet int NOT NULL,
    loaiHoaDon int NOT NULL,
    lyDoKhongDuyet nvarchar(MAX) NULL,
    nguoiDuyet nvarchar(MAX) NULL,
    phuongThucNhap int NOT NULL,
    checkTrangThaiXuLy int NOT NULL,
    checkTrangThaiHoaDon int NOT NULL,
    checkMstNguoiMua int NULL,
    checkDiaChiNguoiMua int NULL,
    checkTenNguoiMua int NULL,
    checkHDonKyDienTu int NOT NULL,
    kiemTraChungThu int NOT NULL,
    kiemTraTenNban int NOT NULL,
    kiemTraMstNban int NOT NULL,
    kiemTraHoatDongNmua int NOT NULL,
    kiemTraHoatDongNban int NOT NULL,
    dsFileDinhKem nvarchar(MAX) NULL,
    fileExcel nvarchar(MAX) NULL
);
