CREATE TABLE CHECK_DIA_CHI_NGUOI_MUA (
    checkDiaChiNguoiMua NUMERIC(18, 0) PRIMARY KEY,
    checkDiaChiNguoiMuaName VARCHAR(50) NOT NULL
);

CREATE TABLE CHECK_HOA_DON_KY_DIEN_TU (
    checkHoaDonKyDienTu NUMERIC(18, 0) PRIMARY KEY,
    checkHoaDonKyDienTuName NVARCHAR(50) NULL
);

CREATE TABLE CHECK_MST_NGUOI_MUA (
    checkMstNguoiMua NUMERIC(18, 0) PRIMARY KEY,
    checkMstNguoiMuaName NVARCHAR(50) NULL
);

CREATE TABLE CHECK_TEN_NGUOI_MUA (
    checkTenNguoiMua NUMERIC(18, 0) PRIMARY KEY,
    checkTenNguoiMuaName NVARCHAR(50) NOT NULL
);

CREATE TABLE CHECK_TRANG_THAI_HOA_DON (
    checkTrangThaiHoaDon NUMERIC(18, 0) PRIMARY KEY,
    checkTrangThaiHoaDonName NVARCHAR(MAX) NOT NULL
);

CREATE TABLE KI_HIEU_MAU_SO_HOA_DON (
    kiHieuMauSoHoaDon NUMERIC(18, 0) PRIMARY KEY,
    kiHieuMauSoHoaDonName NVARCHAR(50) NULL
);

CREATE TABLE LOAI_HOA_DON (
    loaiHoaDon NUMERIC(18, 0) PRIMARY KEY,
    loaiHoaDonName NVARCHAR(50) NOT NULL
);

CREATE TABLE PHUONG_THUC_NHAP (
    phuongThucNhap NUMERIC(18, 0) PRIMARY KEY,
    phuongThucNhapName NVARCHAR(50) NOT NULL
);

CREATE TABLE TINH_CHAT_HOA_DON (
    tinhChatHoaDon NUMERIC(18, 0) PRIMARY KEY,
    tinhChatHoaDonName NVARCHAR(50) NOT NULL
);

CREATE TABLE TRANG_THAI_HOA_DON (
    trangThaiHoaDon NUMERIC(18, 0) PRIMARY KEY,
    trangThaiHoaDonName NVARCHAR(50) NOT NULL
);

CREATE TABLE TRANG_THAI_PHE_DUYET (
    trangThaiPheDuyet NUMERIC(18, 0) PRIMARY KEY,
    trangThaiPheDuyetName NVARCHAR(50) NOT NULL
);
